### ISSUE TITLE
KeyError: 'AddFolderResponse' - (·) U+00B7 char problem

### ISSUE THREAD

**Issue by felixd** [JuniorJPDJ/pyChomikBox#13]
When folder name contains (·) U+00B7 char, folder is not created on Chomikuj:

Folder test name: `TEST·TEST`

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyChomikBox-0.2.1-py3.8.egg/ChomikBox/ChomikBox.py", line 209, in new_folder
  File "/usr/local/lib/python3.8/dist-packages/pyChomikBox-0.2.1-py3.8.egg/ChomikBox/ChomikBox.py", line 428, in new_folder
  File "/usr/local/lib/python3.8/dist-packages/pyChomikBox-0.2.1-py3.8.egg/ChomikBox/ChomikBox.py", line 270, in _send_action
KeyError: 'AddFolderResponse'
```

**Comment by felixd** [comment]
```bash
Traceback (most recent call last):
  File "upload_dir.py", line 87, in <module>
    print(chomikCurrentDir.new_folder(d))
  File "/usr/local/lib/python3.7/dist-packages/pyChomikBox-0.2.1-py3.7.egg/ChomikBox/ChomikBox.py", line 209, in new_folder
  File "/usr/local/lib/python3.7/dist-packages/pyChomikBox-0.2.1-py3.7.egg/ChomikBox/ChomikBox.py", line 428, in new_folder
  File "/usr/local/lib/python3.7/dist-packages/pyChomikBox-0.2.1-py3.7.egg/ChomikBox/ChomikBox.py", line 269, in _send_action
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1289, in _send_request
    body = _encode(body, 'body')
  File "/usr/lib/python3.7/http/client.py", line 170, in _encode
    (name.title(), data[err.start:err.end], name)) from None
UnicodeEncodeError: 'latin-1' codec can't encode character '\u017b' in position 310: Body ('Ż') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```
