### ISSUE TITLE
SeekableHTTPFile seek() is not working

### ISSUE THREAD

**Issue by K5HV** [JuniorJPDJ/pyChomikBox#4]
I've code:
```
from ChomikBox.ChomikBox import Chomik

C = Chomik('...', '...')
C.login()
F = C.list()[0].list()[0].list()[2].open()

print("F: ", type(F))
F.seek(offset=0)

```
but it fails with error:
```
F:  <class 'ChomikBox.utils.SeekableHTTPFile.SeekableHTTPFile'>
Traceback (most recent call last):
  File "/dev/shm/pyChomikBox/test.py", line 8, in <module>
    F.seek(offset=0)
  File "/dev/shm/pyChomikBox/ChomikBox/utils/SeekableHTTPFile.py", line 62, in seek
    self._r.close()
AttributeError: 'NoneType' object has no attribute 'close'
```
It's seems that self._r in SeekableHTTPFile's seek() method is not properly assigned before use.

**Comment by JuniorJPDJ** [comment]
If I remember I fixed it, closing.
